version: '3.9'
services:
  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: myapp-db
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
