import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import TRPCProvider from "@/app/_trpc/Provider"
import { ClerkProvider } from "@clerk/nextjs"
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { CustomSidebarWithSheet } from "@/components/custom-sidebar"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <TRPCProvider>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} bg-[rgba(43,59,74,0.1)] antialiased w-[calc(100dvw-1px)] h-[calc(100dvh-1px)] items-center flex justify-around`}
          >
            <main className="flex items-center justify-center w-full">
              {children}
            </main>
          </body>
        </html>
      </TRPCProvider>
    </ClerkProvider>
  )
}
